import type { Question } from "./types";

export const a1: Question[] = [
  { id: "a1-01", level: "a1", grammarPoint: "be 动词", question: "She ___ a student.", options: ["am", "is", "are", "be"], answer: 1, explanation: "She 是第三人称单数，be 动词用 is。" },
  { id: "a1-02", level: "a1", grammarPoint: "be 动词", question: "I ___ a teacher.", options: ["am", "is", "are", "be"], answer: 0, explanation: "I 搭配 am。" },
  { id: "a1-03", level: "a1", grammarPoint: "be 动词", question: "They ___ from China.", options: ["am", "is", "are", "be"], answer: 2, explanation: "They 是复数，用 are。" },
  { id: "a1-04", level: "a1", grammarPoint: "be 动词否定", question: "He ___ a doctor. He is a nurse.", options: ["is", "isn't", "aren't", "am not"], answer: 1, explanation: "否定 He 用 isn't。" },
  { id: "a1-05", level: "a1", grammarPoint: "be 动词疑问句", question: "___ you a student?", options: ["Am", "Is", "Are", "Be"], answer: 2, explanation: "you 搭配 Are。" },
  { id: "a1-06", level: "a1", grammarPoint: "一般现在时", question: "I ___ coffee every morning.", options: ["drink", "drinks", "drinking", "drank"], answer: 0, explanation: "I 用动词原形 drink。" },
  { id: "a1-07", level: "a1", grammarPoint: "一般现在时", question: "She ___ English every day.", options: ["study", "studys", "studies", "studying"], answer: 2, explanation: "第三人称单数 she 后动词加 es。" },
  { id: "a1-08", level: "a1", grammarPoint: "一般现在时否定", question: "I ___ like coffee.", options: ["don't", "doesn't", "am not", "not"], answer: 0, explanation: "I 是第一人称，否定用 don't。" },
  { id: "a1-09", level: "a1", grammarPoint: "一般现在时否定", question: "He ___ like tea.", options: ["don't", "doesn't", "isn't", "aren't"], answer: 1, explanation: "He 是第三人称，否定用 doesn't。" },
  { id: "a1-10", level: "a1", grammarPoint: "一般现在时疑问句", question: "___ you like pizza?", options: ["Do", "Does", "Are", "Is"], answer: 0, explanation: "you 用 Do 开头。" },
  { id: "a1-11", level: "a1", grammarPoint: "冠词 a / an", question: "I have ___ apple.", options: ["a", "an", "the", "no article"], answer: 1, explanation: "apple 以元音音素开头，用 an。" },
  { id: "a1-12", level: "a1", grammarPoint: "冠词 a / an", question: "She is ___ teacher.", options: ["a", "an", "the", "no article"], answer: 0, explanation: "teacher 以辅音音素开头，用 a。" },
  { id: "a1-13", level: "a1", grammarPoint: "冠词 the", question: "___ sun rises in the east.", options: ["A", "An", "The", "No article"], answer: 2, explanation: "太阳是独一无二的，用 the。" },
  { id: "a1-14", level: "a1", grammarPoint: "名词复数", question: "I have two ___ .", options: ["cat", "cats", "cates", "caties"], answer: 1, explanation: "cat 的复数直接加 s。" },
  { id: "a1-15", level: "a1", grammarPoint: "名词复数", question: "There are three ___ in the room.", options: ["child", "childs", "children", "childrens"], answer: 2, explanation: "child 的复数是不规则变化 children。" },
  { id: "a1-16", level: "a1", grammarPoint: "人称代词", question: "___ is my friend. His name is Tom.", options: ["He", "Him", "His", "She"], answer: 0, explanation: "做主语用主格 He。" },
  { id: "a1-17", level: "a1", grammarPoint: "物主代词", question: "This is ___ book.", options: ["I", "me", "my", "mine"], answer: 2, explanation: "book 是名词，前面用形容词性物主代词 my。" },
  { id: "a1-18", level: "a1", grammarPoint: "this / that", question: "___ is a picture (here). Look!", options: ["This", "That", "Those", "These"], answer: 0, explanation: "离说话人近的单数用 this。" },
  { id: "a1-19", level: "a1", grammarPoint: "these / those", question: "___ are my friends over there.", options: ["This", "That", "These", "Those"], answer: 3, explanation: "离说话人远的复数用 those。" },
  { id: "a1-20", level: "a1", grammarPoint: "There is / There are", question: "___ a book on the table.", options: ["There is", "There are", "It is", "They are"], answer: 0, explanation: "后面是可数名词单数 a book，用 There is。" },
  { id: "a1-21", level: "a1", grammarPoint: "There is / There are", question: "___ many students in the classroom.", options: ["There is", "There are", "It is", "They are"], answer: 1, explanation: "后面是复数 many students，用 There are。" },
  { id: "a1-22", level: "a1", grammarPoint: "介词 in / on / at", question: "My birthday is ___ May.", options: ["in", "on", "at", "by"], answer: 0, explanation: "月份前面用 in。" },
  { id: "a1-23", level: "a1", grammarPoint: "介词 in / on / at", question: "The meeting is ___ 3 o'clock.", options: ["in", "on", "at", "by"], answer: 2, explanation: "具体钟点用 at。" },
  { id: "a1-24", level: "a1", grammarPoint: "介词 in / on / at", question: "I was born ___ January 1st.", options: ["in", "on", "at", "by"], answer: 1, explanation: "具体日期用 on。" },
  { id: "a1-25", level: "a1", grammarPoint: "形容词", question: "This is a ___ book. I like it.", options: ["good", "well", "goods", "goodly"], answer: 0, explanation: "修饰名词 book 用形容词 good。" },
  { id: "a1-26", level: "a1", grammarPoint: "副词", question: "She sings ___.", options: ["beautiful", "beautifully", "beauty", "more beautiful"], answer: 1, explanation: "修饰动词 sings 用副词 beautifully。" },
  { id: "a1-27", level: "a1", grammarPoint: "can 情态动词", question: "I ___ swim.", options: ["can", "am can", "can to", "canning"], answer: 0, explanation: "can 后面直接加动词原形。" },
  { id: "a1-28", level: "a1", grammarPoint: "can 否定", question: "She ___ speak Japanese.", options: ["can't", "don't can", "isn't can", "not can"], answer: 0, explanation: "can 的否定是 cannot / can't。" },
  { id: "a1-29", level: "a1", grammarPoint: "疑问句", question: "___ is your name?", options: ["What", "How", "Who", "Where"], answer: 0, explanation: "问名字用 What。" },
  { id: "a1-30", level: "a1", grammarPoint: "疑问句", question: "___ are you from?", options: ["What", "How", "Who", "Where"], answer: 3, explanation: "问地点用 Where。" },
  { id: "a1-31", level: "a1", grammarPoint: "主谓宾句型", question: "I ___ you.", options: ["love", "loves", "am love", "loving"], answer: 0, explanation: "I 后动词用原形 love，构成主谓宾。" },
  { id: "a1-32", level: "a1", grammarPoint: "形容词", question: "The bag is ___.", options: ["heavy", "heavily", "heaviness", "more heavy"], answer: 0, explanation: "系动词 is 后面用形容词 heavy 做表语。" },
  { id: "a1-33", level: "a1", grammarPoint: "一般疑问句回答", question: "Are you happy? Yes, I ___.", options: ["am", "are", "is", "be"], answer: 0, explanation: "问 Are you…？肯定回答 Yes, I am。" },
  { id: "a1-34", level: "a1", grammarPoint: "数量表达", question: "I have ___ money.", options: ["some", "any", "a", "an"], answer: 0, explanation: "肯定句中用 some。" },
  { id: "a1-35", level: "a1", grammarPoint: "数量表达", question: "Do you have ___ questions?", options: ["some", "any", "a", "an"], answer: 1, explanation: "疑问句中常用 any。" },
];
