import type { Question } from "./types";

export const a2: Question[] = [
  { id: "a2-01", level: "a2", grammarPoint: "一般过去时", question: "I ___ to the park yesterday.", options: ["go", "goes", "went", "gone"], answer: 2, explanation: "yesterday 表示过去，go 的过去式是 went。" },
  { id: "a2-02", level: "a2", grammarPoint: "一般过去时", question: "She ___ a movie last night.", options: ["watch", "watches", "watched", "watching"], answer: 2, explanation: "last night 表示过去，watch 加 ed。" },
  { id: "a2-03", level: "a2", grammarPoint: "一般过去时否定", question: "I ___ my homework yesterday.", options: ["didn't finish", "not finish", "didn't finished", "don't finish"], answer: 0, explanation: "过去时否定用 didn't + 动词原形。" },
  { id: "a2-04", level: "a2", grammarPoint: "一般过去时疑问句", question: "___ you go to school yesterday?", options: ["Do", "Does", "Did", "Are"], answer: 2, explanation: "过去时疑问句用 Did 开头。" },
  { id: "a2-05", level: "a2", grammarPoint: "不规则过去式", question: "She ___ a great time at the party.", options: ["haved", "had", "has", "having"], answer: 1, explanation: "have 的过去式是 had。" },
  { id: "a2-06", level: "a2", grammarPoint: "现在进行时", question: "Look! It ___ outside.", options: ["rain", "rains", "is raining", "rained"], answer: 2, explanation: "Look! 强调正在发生，用现在进行时。" },
  { id: "a2-07", level: "a2", grammarPoint: "现在进行时", question: "The children ___ a game now.", options: ["play", "plays", "are playing", "played"], answer: 2, explanation: "now 表示正在发生，children 是复数，用 are playing。" },
  { id: "a2-08", level: "a2", grammarPoint: "现在进行时否定", question: "He ___ right now.", options: ["isn't working", "doesn't working", "not working", "don't work"], answer: 0, explanation: "现在进行时否定在 be 动词后加 not。" },
  { id: "a2-09", level: "a2", grammarPoint: "going to 将来时", question: "We ___ travel to Japan next year.", options: ["going to", "are going to", "will going to", "go to"], answer: 1, explanation: "be going to 表示计划，We 搭配 are。" },
  { id: "a2-10", level: "a2", grammarPoint: "going to 将来时", question: "It's cloudy. It ___ rain.", options: ["is going to", "will going to", "goes to", "is going"], answer: 0, explanation: "根据迹象推测用 is going to。" },
  { id: "a2-11", level: "a2", grammarPoint: "比较级", question: "She is ___ than me.", options: ["tall", "taller", "tallest", "more tall"], answer: 1, explanation: "than 前面用比较级 taller。" },
  { id: "a2-12", level: "a2", grammarPoint: "比较级", question: "This book is ___ than that one.", options: ["interestinger", "more interesting", "most interesting", "interesting"], answer: 1, explanation: "多音节词比较级用 more。" },
  { id: "a2-13", level: "a2", grammarPoint: "最高级", question: "She is the ___ student in our class.", options: ["good", "better", "best", "well"], answer: 2, explanation: "全班范围内比较用最高级 best。" },
  { id: "a2-14", level: "a2", grammarPoint: "可数 / 不可数", question: "I need ___ water.", options: ["a", "an", "some", "many"], answer: 2, explanation: "water 是不可数名词，用 some。" },
  { id: "a2-15", level: "a2", grammarPoint: "可数 / 不可数", question: "How ___ apples do you want?", options: ["much", "many", "some", "any"], answer: 1, explanation: "apples 是可数名词复数，用 many。" },
  { id: "a2-16", level: "a2", grammarPoint: "可数 / 不可数", question: "How ___ milk do you need?", options: ["much", "many", "some", "few"], answer: 0, explanation: "milk 不可数，用 much。" },
  { id: "a2-17", level: "a2", grammarPoint: "some / any", question: "I have ___ good friends.", options: ["some", "any", "no", "every"], answer: 0, explanation: "肯定句用 some。" },
  { id: "a2-18", level: "a2", grammarPoint: "some / any", question: "I don't have ___ money.", options: ["some", "any", "no", "every"], answer: 1, explanation: "否定句用 any。" },
  { id: "a2-19", level: "a2", grammarPoint: "频率副词", question: "I ___ get up at 7 am. (100%)", options: ["sometimes", "usually", "always", "never"], answer: 2, explanation: "100% 的频率用 always。" },
  { id: "a2-20", level: "a2", grammarPoint: "频率副词", question: "I ___ eat fast food. (0%)", options: ["always", "usually", "sometimes", "never"], answer: 3, explanation: "0% 的频率用 never。" },
  { id: "a2-21", level: "a2", grammarPoint: "情态动词 can", question: "I ___ hear you. Please speak louder.", options: ["can't", "mustn't", "shouldn't", "don't"], answer: 0, explanation: "听不到用 can't，表示能力上的否定。" },
  { id: "a2-22", level: "a2", grammarPoint: "have to", question: "I ___ finish my homework before 9 pm.", options: ["have to", "has to", "must to", "haveto"], answer: 0, explanation: "I 用 have to 表示必须。" },
  { id: "a2-23", level: "a2", grammarPoint: "过去进行时", question: "I ___ TV when you called.", options: ["watched", "was watching", "am watching", "watch"], answer: 1, explanation: "过去某一时刻正在发生，用过去进行时。" },
  { id: "a2-24", level: "a2", grammarPoint: "过去进行时", question: "They ___ football at 3 pm yesterday.", options: ["play", "played", "were playing", "are playing"], answer: 2, explanation: "过去具体时间正在发生，复数用 were playing。" },
  { id: "a2-25", level: "a2", grammarPoint: "物主代词", question: "This is my book. That is ___.", options: ["your", "yours", "you", "your book"], answer: 1, explanation: "后面没名词，用名词性物主代词 yours。" },
  { id: "a2-26", level: "a2", grammarPoint: "反身代词", question: "I hurt ___ while cooking.", options: ["myself", "yourself", "himself", "itself"], answer: 0, explanation: "主语和宾语是同一人，用反身代词 myself。" },
  { id: "a2-27", level: "a2", grammarPoint: "不定式作目的", question: "I went to the store ___ some milk.", options: ["buy", "to buy", "buying", "bought"], answer: 1, explanation: "表示目的用不定式 to buy。" },
  { id: "a2-28", level: "a2", grammarPoint: "形容词顺序", question: "She has ___ hair.", options: ["long beautiful black", "beautiful long black", "black beautiful long", "beautiful black long"], answer: 1, explanation: "形容词顺序：主观评价→长短→颜色。" },
  { id: "a2-29", level: "a2", grammarPoint: "would like", question: "I ___ a cup of tea, please.", options: ["would like", "am like", "will liking", "liked"], answer: 0, explanation: "would like 表示想要，后面接名词。" },
  { id: "a2-30", level: "a2", grammarPoint: "so / neither", question: "I like coffee. — ___.", options: ["So do I", "So am I", "Neither do I", "So I do"], answer: 0, explanation: "肯定句回应用 So + 助动词 + I。" },
  { id: "a2-31", level: "a2", grammarPoint: "不定式", question: "It's important ___ English.", options: ["learn", "to learn", "learning", "learned"], answer: 1, explanation: "It's + 形容词 + to do 是不定式常用句型。" },
  { id: "a2-32", level: "a2", grammarPoint: "动名词作主语", question: "___ is good for health.", options: ["Swim", "To swimming", "Swimming", "Swam"], answer: 2, explanation: "动名词 swimming 做主语。" },
  { id: "a2-33", level: "a2", grammarPoint: "as...as", question: "She is ___ tall ___ her sister.", options: ["as ... as", "so ... as", "more ... than", "the ... of"], answer: 0, explanation: "as + 形容词 + as 表示两者程度相同。" },
  { id: "a2-34", level: "a2", grammarPoint: "序数词", question: "December is the ___ month of the year.", options: ["twelve", "twelfth", "twentieth", "second"], answer: 1, explanation: "第十二个月用序数词 twelfth。" },
  { id: "a2-35", level: "a2", grammarPoint: "原因从句", question: "I stayed home ___ it was raining.", options: ["because", "so", "but", "and"], answer: 0, explanation: "说明原因用 because。" },
];
