import type { Question } from "./types";

export const b1: Question[] = [
  { id: "b1-01", level: "b1", grammarPoint: "现在完成时", question: "I ___ been to Japan twice.", options: ["have", "has", "had", "am"], answer: 0, explanation: "I 用 have + 过去分词。" },
  { id: "b1-02", level: "b1", grammarPoint: "现在完成时", question: "She ___ finished her homework.", options: ["have", "has", "had", "is"], answer: 1, explanation: "She 是第三人称单数，用 has。" },
  { id: "b1-03", level: "b1", grammarPoint: "现在完成时", question: "I ___ this movie yet.", options: ["have seen", "haven't seen", "saw", "didn't see"], answer: 1, explanation: "yet 用于否定句，现在完成时 haven't seen。" },
  { id: "b1-04", level: "b1", grammarPoint: "现在完成时", question: "___ you ever eaten sushi?", options: ["Have", "Has", "Did", "Are"], answer: 0, explanation: "ever 是现在完成时标志，you 用 Have。" },
  { id: "b1-05", level: "b1", grammarPoint: "for / since", question: "I have lived here ___ 2018.", options: ["for", "since", "in", "from"], answer: 1, explanation: "2018 是时间点，用 since。" },
  { id: "b1-06", level: "b1", grammarPoint: "for / since", question: "I have worked here ___ five years.", options: ["for", "since", "in", "from"], answer: 0, explanation: "five years 是一段时间，用 for。" },
  { id: "b1-07", level: "b1", grammarPoint: "现在完成进行时", question: "I ___ English for three years.", options: ["study", "am studying", "have been studying", "studied"], answer: 2, explanation: "持续了三年的动作用现在完成进行时。" },
  { id: "b1-08", level: "b1", grammarPoint: "will 将来时", question: "I ___ you tomorrow.", options: ["will call", "call", "am call", "called"], answer: 0, explanation: "tomorrow 表示将来，will + 动词原形。" },
  { id: "b1-09", level: "b1", grammarPoint: "will vs going to", question: "I think it ___ rain tomorrow.", options: ["will", "is going to", "goes to", "rains"], answer: 0, explanation: "预测不确定的事情用 will。" },
  { id: "b1-10", level: "b1", grammarPoint: "第一条件句", question: "If it rains, I ___ an umbrella.", options: ["bring", "will bring", "would bring", "brought"], answer: 1, explanation: "if + 现在时，主句用 will。" },
  { id: "b1-11", level: "b1", grammarPoint: "第一条件句", question: "If you study hard, you ___ the exam.", options: ["pass", "will pass", "would pass", "passed"], answer: 1, explanation: "真实条件句，主句用 will + 动词原形。" },
  { id: "b1-12", level: "b1", grammarPoint: "第二条件句", question: "If I won the lottery, I ___ a car.", options: ["buy", "will buy", "would buy", "bought"], answer: 2, explanation: "虚拟条件句，主句用 would。" },
  { id: "b1-13", level: "b1", grammarPoint: "被动语态", question: "The book ___ by Mark Twain.", options: ["wrote", "is written", "was written", "writing"], answer: 2, explanation: "书被写，过去动作，用 was written。" },
  { id: "b1-14", level: "b1", grammarPoint: "被动语态", question: "English ___ all over the world.", options: ["speaks", "is spoken", "was spoken", "speak"], answer: 1, explanation: "英语被说，一般事实，用 is spoken。" },
  { id: "b1-15", level: "b1", grammarPoint: "定语从句", question: "The girl ___ is wearing a red dress is my sister.", options: ["which", "who", "whom", "whose"], answer: 1, explanation: "修饰人的主语，用 who。" },
  { id: "b1-16", level: "b1", grammarPoint: "定语从句", question: "The book ___ I bought is interesting.", options: ["who", "which", "whom", "whose"], answer: 1, explanation: "修饰物的宾语，用 which。" },
  { id: "b1-17", level: "b1", grammarPoint: "定语从句", question: "The man ___ car was stolen called the police.", options: ["who", "which", "that", "whose"], answer: 3, explanation: "表示所属关系用 whose。" },
  { id: "b1-18", level: "b1", grammarPoint: "should / must", question: "You ___ see a doctor. You look sick.", options: ["must", "should", "can", "might"], answer: 1, explanation: "建议用 should，比 must 语气弱。" },
  { id: "b1-19", level: "b1", grammarPoint: "must / have to", question: "You ___ wear a seatbelt while driving. It's the law.", options: ["must", "should", "could", "might"], answer: 0, explanation: "法律规定必须用 must。" },
  { id: "b1-20", level: "b1", grammarPoint: "情态动词", question: "You ___ drive after drinking. It's dangerous.", options: ["mustn't", "don't have to", "shouldn't", "couldn't"], answer: 0, explanation: "禁止做某事用 mustn't。" },
  { id: "b1-21", level: "b1", grammarPoint: "used to", question: "I ___ play basketball when I was young.", options: ["used to", "use to", "was used to", "am used to"], answer: 0, explanation: "used to do 表示过去经常但现在不做了。" },
  { id: "b1-22", level: "b1", grammarPoint: "间接引语", question: "She said she ___ tired.", options: ["is", "was", "has been", "will be"], answer: 1, explanation: "间接引语中时态后推，is 变成 was。" },
  { id: "b1-23", level: "b1", grammarPoint: "间接引语", question: "He said he ___ come to the party.", options: ["will", "would", "can", "may"], answer: 1, explanation: "间接引语中 will 变成 would。" },
  { id: "b1-24", level: "b1", grammarPoint: "连接词", question: "I was tired, ___ I went to bed early.", options: ["so", "because", "but", "although"], answer: 0, explanation: "结果关系用 so。" },
  { id: "b1-25", level: "b1", grammarPoint: "连接词", question: "___ it was raining, we went out.", options: ["Because", "Although", "So", "If"], answer: 1, explanation: "转折让步用 Although。" },
  { id: "b1-26", level: "b1", grammarPoint: "时间状语从句", question: "I will call you ___ I arrive.", options: ["when", "if", "because", "although"], answer: 0, explanation: "时间关系用 when。" },
  { id: "b1-27", level: "b1", grammarPoint: "比较结构", question: "She is ___ intelligent ___ her brother.", options: ["as ... than", "more ... as", "more ... than", "most ... than"], answer: 2, explanation: "比较级 + than。" },
  { id: "b1-28", level: "b1", grammarPoint: "目的状语", question: "I saved money ___ buy a new phone.", options: ["for", "to", "so that", "in order"], answer: 2, explanation: "so that + 从句表示目的。注意这里 so that 是对的。" },
  { id: "b1-29", level: "b1", grammarPoint: "too / enough", question: "It's ___ cold to go outside.", options: ["too", "enough", "very", "so"], answer: 0, explanation: "too + 形容词 + to do 表示太……而不能。" },
  { id: "b1-30", level: "b1", grammarPoint: "so...that", question: "It was ___ hot ___ I couldn't sleep.", options: ["so ... that", "too ... that", "such ... that", "enough ... that"], answer: 0, explanation: "so + 形容词 + that 表示如此……以至于。" },
  { id: "b1-31", level: "b1", grammarPoint: "被动语态", question: "The letter ___ yesterday.", options: ["sent", "was sent", "is sent", "sends"], answer: 1, explanation: "信被寄出，过去时间，用 was sent。" },
  { id: "b1-32", level: "b1", grammarPoint: "情态动词", question: "You ___ be hungry. You just ate.", options: ["can't", "mustn't", "shouldn't", "needn't"], answer: 0, explanation: "逻辑否定推断用 can't（不可能）。" },
  { id: "b1-33", level: "b1", grammarPoint: "情态动词", question: "She ___ be at home. Her car is in the driveway.", options: ["must", "can", "should", "might"], answer: 0, explanation: "逻辑肯定推断用 must（一定是）。" },
  { id: "b1-34", level: "b1", grammarPoint: "动名词 / 不定式", question: "I enjoy ___ books.", options: ["read", "to read", "reading", "readed"], answer: 2, explanation: "enjoy 后面接动名词。" },
  { id: "b1-35", level: "b1", grammarPoint: "动名词 / 不定式", question: "He decided ___ a new job.", options: ["get", "to get", "getting", "got"], answer: 1, explanation: "decide 后面接不定式。" },
];
