import type { Question } from "./types";

export const b2: Question[] = [
  { id: "b2-01", level: "b2", grammarPoint: "过去完成时", question: "I realized I ___ my keys at home.", options: ["left", "had left", "have left", "was leaving"], answer: 1, explanation: "过去的过去，用过去完成时 had left。" },
  { id: "b2-02", level: "b2", grammarPoint: "过去完成时", question: "She ___ English before she moved to London.", options: ["studied", "had studied", "has studied", "was studying"], answer: 1, explanation: "搬去之前已经学过了，过去的过去。" },
  { id: "b2-03", level: "b2", grammarPoint: "过去完成时", question: "By the time I arrived, the meeting ___.", options: ["already started", "had already started", "has started", "starts"], answer: 1, explanation: "我到达之前会议已经开始了。" },
  { id: "b2-04", level: "b2", grammarPoint: "将来完成时", question: "By 2028, I ___ here for 10 years.", options: ["work", "will work", "will have worked", "have worked"], answer: 2, explanation: "到将来某时间为止已完成，用将来完成时。" },
  { id: "b2-05", level: "b2", grammarPoint: "第三条件句", question: "If I had studied, I ___ the exam.", options: ["passed", "would pass", "would have passed", "had passed"], answer: 2, explanation: "与过去相反的假设，主句用 would have + 过去分词。" },
  { id: "b2-06", level: "b2", grammarPoint: "混合条件句", question: "If I had taken that job, I ___ rich now.", options: ["would be", "would have been", "will be", "am"], answer: 0, explanation: "条件句与过去相反但主句与现在相反，用 would be。" },
  { id: "b2-07", level: "b2", grammarPoint: "被动语态", question: "The house ___ at the moment.", options: ["is painting", "is being painted", "paints", "painted"], answer: 1, explanation: "现在正在被粉刷，用被动进行时。" },
  { id: "b2-08", level: "b2", grammarPoint: "被动语态", question: "The new bridge ___ by next year.", options: ["will complete", "will be completed", "will have completed", "completes"], answer: 1, explanation: "桥将被完成，将来被动。" },
  { id: "b2-09", level: "b2", grammarPoint: "非限制性定语从句", question: "My mother, ___ is 60, still works.", options: ["that", "which", "who", "whom"], answer: 2, explanation: "非限制性定语从句修饰人用 who，不能用 that。" },
  { id: "b2-10", level: "b2", grammarPoint: "非限制性定语从句", question: "The Eiffel Tower, ___ is in Paris, is beautiful.", options: ["that", "which", "what", "where"], answer: 1, explanation: "非限制性定语从句修饰物用 which。" },
  { id: "b2-11", level: "b2", grammarPoint: "情态动词 + have", question: "She ___ missed the train. She left late.", options: ["must have", "should have", "could have", "would have"], answer: 0, explanation: "对过去肯定的推论用 must have。" },
  { id: "b2-12", level: "b2", grammarPoint: "情态动词 + have", question: "You ___ told me earlier. I could have helped.", options: ["must have", "should have", "could have", "would have"], answer: 1, explanation: "过去本应该做但没做，用 should have。" },
  { id: "b2-13", level: "b2", grammarPoint: "情态动词 + have", question: "He ___ gone home. The lights are off.", options: ["must have", "should have", "could have", "might have"], answer: 3, explanation: "对过去不那么确信的推测用 might have。" },
  { id: "b2-14", level: "b2", grammarPoint: "间接引语", question: "She told me she ___ the next day.", options: ["will leave", "would leave", "leaves", "left"], answer: 1, explanation: "间接引语时态后推，will → would。" },
  { id: "b2-15", level: "b2", grammarPoint: "间接引语疑问句", question: "He asked me ___ I liked coffee.", options: ["if", "that", "what", "which"], answer: 0, explanation: "一般疑问句变间接引语用 if 连接。" },
  { id: "b2-16", level: "b2", grammarPoint: "动名词 vs 不定式", question: "I remember ___ the door before leaving.", options: ["lock", "to lock", "locking", "locked"], answer: 2, explanation: "remember doing 记得做过某事。" },
  { id: "b2-17", level: "b2", grammarPoint: "动名词 vs 不定式", question: "I remember ___ the door when I leave.", options: ["lock", "to lock", "locking", "locked"], answer: 1, explanation: "remember to do 记得要做某事。" },
  { id: "b2-18", level: "b2", grammarPoint: "动名词 / 不定式", question: "I stopped ___ coffee because it kept me awake.", options: ["drink", "to drink", "drinking", "drank"], answer: 2, explanation: "stop doing 停止做某事。" },
  { id: "b2-19", level: "b2", grammarPoint: "虚拟语气", question: "I wish I ___ fly.", options: ["can", "could", "will", "would"], answer: 1, explanation: "wish 后接虚拟语气，用 could。" },
  { id: "b2-20", level: "b2", grammarPoint: "虚拟语气", question: "I wish I ___ more time yesterday.", options: ["have", "had", "had had", "have had"], answer: 2, explanation: "对过去事实的愿望，用 had done。" },
  { id: "b2-21", level: "b2", grammarPoint: "倒装句", question: "___ had I left when it started raining.", options: ["No sooner", "Hardly", "Never", "Only"], answer: 0, explanation: "No sooner...than... 表示一……就……" },
  { id: "b2-22", level: "b2", grammarPoint: "倒装句", question: "Not until I got home ___ I had left my phone.", options: ["I realized", "I did realize", "did I realize", "realized I"], answer: 2, explanation: "Not until 放在句首，主句要部分倒装。" },
  { id: "b2-23", level: "b2", grammarPoint: "分词作定语", question: "The ___ boy is my brother.", options: ["crying", "cried", "cry", "is crying"], answer: 0, explanation: "现在分词 crying 做定语修饰 boy。" },
  { id: "b2-24", level: "b2", grammarPoint: "分词作状语", question: "___ by the view, she took a photo.", options: ["Impressing", "Impressed", "To impress", "Being impress"], answer: 1, explanation: "她被景色打动，过去分词表示被动。" },
  { id: "b2-25", level: "b2", grammarPoint: "独立主格", question: "The weather ___ nice, we went for a walk.", options: ["is", "was", "being", "been"], answer: 2, explanation: "独立主格结构用 being。" },
  { id: "b2-26", level: "b2", grammarPoint: "强调句", question: "It was Tom ___ broke the window.", options: ["who", "which", "whom", "whose"], answer: 0, explanation: "It is/was...that/who 强调句型，人用 who。" },
  { id: "b2-27", level: "b2", grammarPoint: "强调句", question: "It was yesterday ___ I met her.", options: ["when", "that", "which", "where"], answer: 1, explanation: "强调句型中，被强调的部分是时间也用 that。" },
  { id: "b2-28", level: "b2", grammarPoint: "同位语从句", question: "The news ___ he won surprised everyone.", options: ["which", "that", "what", "who"], answer: 1, explanation: "同位语从句说明 news 的内容，用 that。" },
  { id: "b2-29", level: "b2", grammarPoint: "让步状语", question: "___ she was tired, she kept working.", options: ["Despite", "Although", "Because", "Therefore"], answer: 1, explanation: "让步关系用 Although。" },
  { id: "b2-30", level: "b2", grammarPoint: "方式状语", question: "You should do ___ I told you.", options: ["like", "as", "such as", "for example"], answer: 1, explanation: "方式状语用 as（正如）。" },
  { id: "b2-31", level: "b2", grammarPoint: "suggest 虚拟", question: "I suggested that he ___ a doctor.", options: ["see", "sees", "saw", "seeing"], answer: 0, explanation: "suggest 后接 that 从句用动词原形表虚拟。" },
  { id: "b2-32", level: "b2", grammarPoint: "recommend 虚拟", question: "The doctor recommended that I ___ more water.", options: ["drink", "drinks", "drank", "drinking"], answer: 0, explanation: "recommend 后接 that 从句用动词原形。" },
  { id: "b2-33", level: "b2", grammarPoint: "名词性从句", question: 'What she said surprised everyone.', options: ["What", "That", "Which", "Who"], answer: 0, explanation: "what 引导主语从句表示'她所说的'。" },
  { id: "b2-34", level: "b2", grammarPoint: "名词性从句", question: "The problem is ___ we don't have enough time.", options: ["what", "that", "which", "when"], answer: 1, explanation: "表语从句中 that 不充当成分只起连接作用。" },
  { id: "b2-35", level: "b2", grammarPoint: "whether / if", question: "I don't know ___ he will come.", options: ["that", "weather", "whether", "what"], answer: 2, explanation: "whether 表示'是否'，引导宾语从句。" },
];
