import type { Question } from "./types";

export const c1: Question[] = [
  { id: "c1-01", level: "c1", grammarPoint: "倒装句", question: "___ had she arrived than the phone rang.", options: ["Hardly", "No sooner", "Not until", "Never"], answer: 1, explanation: "No sooner...than... 固定搭配，表示一……就……" },
  { id: "c1-02", level: "c1", grammarPoint: "倒装句", question: "___ had she finished the report when her boss asked for changes.", options: ["No sooner", "Hardly", "Scarcely", "Barely"], answer: 1, explanation: "Hardly...when... 固定搭配。" },
  { id: "c1-03", level: "c1", grammarPoint: "倒装句", question: "Not only ___ late, but he also forgot the documents.", options: ["he was", "was he", "he did", "did he"], answer: 1, explanation: "Not only 放在句首，句子倒装。" },
  { id: "c1-04", level: "c1", grammarPoint: "倒装句", question: "Seldom ___ such a beautiful sunset.", options: ["I have seen", "have I seen", "I saw", "saw I"], answer: 1, explanation: "Seldom 放在句首，倒装。" },
  { id: "c1-05", level: "c1", grammarPoint: "倒装句", question: "Only after the meeting ___ the truth.", options: ["I realized", "did I realize", "I did realize", "realized I"], answer: 1, explanation: "Only + 状语位于句首，主句倒装。" },
  { id: "c1-06", level: "c1", grammarPoint: "虚拟语气", question: "If it ___ for your help, I would have failed.", options: ["hadn't been", "wasn't", "weren't", "hasn't been"], answer: 0, explanation: "与过去相反的虚拟，从句用 had done。" },
  { id: "c1-07", level: "c1", grammarPoint: "虚拟语气", question: "I'd rather you ___ smoke in the room.", options: ["don't", "didn't", "wouldn't", "not"], answer: 1, explanation: "would rather + 从句用过去时表虚拟。" },
  { id: "c1-08", level: "c1", grammarPoint: "虚拟语气", question: "It's high time we ___ something about it.", options: ["do", "did", "have done", "will do"], answer: 1, explanation: "It's high time + 过去时表虚拟。" },
  { id: "c1-09", level: "c1", grammarPoint: "虚拟语气", question: "He talks as if he ___ everything.", options: ["knows", "knew", "has known", "will know"], answer: 1, explanation: "as if 后用过去时表示与现在相反的虚拟。" },
  { id: "c1-10", level: "c1", grammarPoint: "分词从句", question: "___ by the beauty of the city, she decided to stay.", options: ["Fascinating", "Fascinated", "To fascinate", "Being fascinate"], answer: 1, explanation: "过去分词表示被动含义。" },
  { id: "c1-11", level: "c1", grammarPoint: "分词从句", question: "___ the book, I realized why it was a bestseller.", options: ["Read", "Having read", "Have read", "To read"], answer: 1, explanation: "Having done 表主动且先于主句动作。" },
  { id: "c1-12", level: "c1", grammarPoint: "分词从句", question: "___ carefully, the report was error-free.", options: ["Writing", "Written", "To write", "Having writing"], answer: 1, explanation: "报告被仔细写，过去分词表被动。" },
  { id: "c1-13", level: "c1", grammarPoint: "连接词", question: "The project was a success, ___ the initial difficulties.", options: ["because of", "despite", "although", "since"], answer: 1, explanation: "despite + 名词短语表让步。" },
  { id: "c1-14", level: "c1", grammarPoint: "连接词", question: "___ he is talented, he lacks motivation.", options: ["Despite", "In spite of", "While", "Because"], answer: 2, explanation: "While 放句首表转折对比。" },
  { id: "c1-15", level: "c1", grammarPoint: "强调倒装", question: "___ is the problem that needs to be solved.", options: ["This", "It", "What", "That"], answer: 1, explanation: "It is...that 强调句型。" },
  { id: "c1-16", level: "c1", grammarPoint: "名词从句", question: "___ we need is more time.", options: ["What", "That", "Which", "Who"], answer: 0, explanation: "what 从句做主句的主语。" },
  { id: "c1-17", level: "c1", grammarPoint: "名词从句", question: "The fact ___ he passed the exam surprised everyone.", options: ["which", "that", "what", "whether"], answer: 1, explanation: "同位语从句说明 fact 的内容，用 that。" },
  { id: "c1-18", level: "c1", grammarPoint: "固定句型", question: "The more you practice, ___ you become.", options: ["the better", "better", "the best", "more better"], answer: 0, explanation: "the + 比较级，the + 比较级 表示越……越……" },
  { id: "c1-19", level: "c1", grammarPoint: "固定句型", question: "___, I would never agree to that plan.", options: ["If I am you", "If I was you", "Were I you", "I were you"], answer: 2, explanation: "虚拟倒装，If I were you → Were I you。" },
  { id: "c1-20", level: "c1", grammarPoint: "固定句型", question: "___ for your intervention, the situation would have worsened.", options: ["If it hadn't", "Had it not been", "Were it not", "If it wasn't"], answer: 1, explanation: "虚拟语气省去 if 后倒装。" },
  { id: "c1-21", level: "c1", grammarPoint: "含蓄条件", question: "She would have gone, but she ___ sick.", options: ["were", "had been", "was", "would be"], answer: 2, explanation: "but 引导的含蓄条件句用陈述语气。" },
  { id: "c1-22", level: "c1", grammarPoint: "含蓄条件", question: "A true friend ___ you in trouble.", options: ["would not leave", "will not leave", "did not leave", "has not left"], answer: 0, explanation: "名词短语表隐含的条件，用 would。" },
  { id: "c1-23", level: "c1", grammarPoint: "省略", question: "I earn more than I ___ five years ago.", options: ["do", "have", "did", "was"], answer: 2, explanation: "比较状语从句中助动词代替整个谓语，过去时用 did。" },
  { id: "c1-24", level: "c1", grammarPoint: "省略", question: "Can you help me? — I'm afraid ___.", options: ["not", "no", "don't", "cannot"], answer: 0, explanation: "I'm afraid not 是固定省略表达。" },
  { id: "c1-25", level: "c1", grammarPoint: "语体", question: "It is essential that every student ___ the rules.", options: ["understands", "understand", "understood", "understanding"], answer: 1, explanation: "essential that + 动词原形，表虚拟。" },
  { id: "c1-26", level: "c1", grammarPoint: "语体", question: "The manager suggested that the report ___ rewritten.", options: ["is", "be", "was", "will be"], answer: 1, explanation: "suggest that + (should) + 动词原形。" },
  { id: "c1-27", level: "c1", grammarPoint: "惯用搭配", question: "___ the weather, we'll have the party indoors.", options: ["Thanks to", "Due to", "Regardless of", "In spite"], answer: 2, explanation: "Regardless of 表示无论、不管。" },
  { id: "c1-28", level: "c1", grammarPoint: "惯用搭配", question: "She is ___ a musician ___ a painter.", options: ["neither ... or", "either ... nor", "not only ... but also", "as ... as"], answer: 2, explanation: "not only...but also 表示不仅……而且……" },
  { id: "c1-29", level: "c1", grammarPoint: "惯用搭配", question: "We decided to postpone ___ a decision.", options: ["make", "making", "to make", "made"], answer: 1, explanation: "postpone 后面接动名词。" },
  { id: "c1-30", level: "c1", grammarPoint: "惯用搭配", question: "You can't help ___ impressed by her performance.", options: ["being", "be", "to be", "been"], answer: 0, explanation: "can't help doing 忍不住做某事。" },
  { id: "c1-31", level: "c1", grammarPoint: "惯用搭配", question: "We look forward ___ from you.", options: ["to hear", "to hearing", "hear", "hearing"], answer: 1, explanation: "look forward to 中的 to 是介词，后接动名词。" },
  { id: "c1-32", level: "c1", grammarPoint: "惯用搭配", question: "He is accustomed ___ in a big city.", options: ["live", "to live", "to living", "living"], answer: 2, explanation: "be accustomed to + 动名词。" },
  { id: "c1-33", level: "c1", grammarPoint: "连接词", question: "The company is expanding abroad ___ domestic sales have declined.", options: ["therefore", "nevertheless", "whereas", "furthermore"], answer: 2, explanation: "whereas 表对比关系。" },
  { id: "c1-34", level: "c1", grammarPoint: "惯用搭配", question: "Hardly ___ finished breakfast when the doorbell rang.", options: ["I had", "had I", "I have", "have I"], answer: 1, explanation: "Hardly 放句首，要用倒装。" },
  { id: "c1-35", level: "c1", grammarPoint: "惯用搭配", question: "It's no use ___ about the past.", options: ["to worry", "worrying", "worried", "worry"], answer: 1, explanation: "It's no use + 动名词，表示做某事没用。" },
];
