export type IrregularVerb = {
  verb: string;
  chinese: string;
  past: string;
};

export const irregularVerbs: IrregularVerb[] = [
  { verb: "am/is", chinese: "是", past: "was" },
  { verb: "are", chinese: "是", past: "were" },
  { verb: "become", chinese: "变成", past: "became" },
  { verb: "come", chinese: "来", past: "came" },
  { verb: "begin", chinese: "开始", past: "began" },
  { verb: "break", chinese: "打碎", past: "broke" },
  { verb: "do/does", chinese: "做", past: "did" },
  { verb: "bring", chinese: "带来", past: "brought" },
  { verb: "buy", chinese: "买", past: "bought" },
  { verb: "think", chinese: "认为", past: "thought" },
  { verb: "fight", chinese: "打架", past: "fought" },
  { verb: "catch", chinese: "捉住", past: "caught" },
  { verb: "teach", chinese: "教", past: "taught" },
  { verb: "can", chinese: "能", past: "could" },
  { verb: "draw", chinese: "画", past: "drew" },
  { verb: "drink", chinese: "喝，饮", past: "drank" },
  { verb: "build", chinese: "建造", past: "built" },
  { verb: "lend", chinese: "借出", past: "lent" },
  { verb: "send", chinese: "送，派", past: "sent" },
  { verb: "spend", chinese: "花费", past: "spent" },
  { verb: "eat", chinese: "吃", past: "ate" },
  { verb: "fall", chinese: "跌，落", past: "fell" },
  { verb: "find", chinese: "找到", past: "found" },
  { verb: "dream", chinese: "梦想", past: "dreamed" },
  { verb: "hear", chinese: "听见", past: "heard" },
  { verb: "learn", chinese: "学习", past: "learned" },
  { verb: "show", chinese: "展示", past: "showed" },
  { verb: "smell", chinese: "嗅，闻", past: "smelt/smelled" },
  { verb: "fly", chinese: "飞", past: "flew" },
  { verb: "go", chinese: "去", past: "went" },
  { verb: "read", chinese: "阅读", past: "read" },
  { verb: "cut", chinese: "切，割", past: "cut" },
  { verb: "put", chinese: "放", past: "put" },
  { verb: "set", chinese: "安置", past: "set" },
  { verb: "let", chinese: "让", past: "let" },
  { verb: "may", chinese: "可能", past: "might" },
  { verb: "lie", chinese: "躺", past: "lay" },
  { verb: "give", chinese: "给", past: "gave" },
  { verb: "forget", chinese: "忘记", past: "forgot" },
  { verb: "get", chinese: "得到", past: "got" },
  { verb: "grow", chinese: "生长", past: "grew" },
  { verb: "drive", chinese: "驾驶", past: "drove" },
  { verb: "write", chinese: "写", past: "wrote" },
  { verb: "lose", chinese: "失去", past: "lost" },
  { verb: "pay", chinese: "支付", past: "paid" },
  { verb: "say", chinese: "说", past: "said" },
  { verb: "sit", chinese: "坐", past: "sat" },
  { verb: "sing", chinese: "唱", past: "sang" },
  { verb: "swim", chinese: "游泳", past: "swam" },
  { verb: "hold", chinese: "举行", past: "held" },
  { verb: "feel", chinese: "感觉", past: "felt" },
  { verb: "keep", chinese: "保持", past: "kept" },
  { verb: "leave", chinese: "离开", past: "left" },
  { verb: "sleep", chinese: "睡", past: "slept" },
  { verb: "sweep", chinese: "打扫", past: "swept" },
  { verb: "have/has", chinese: "有", past: "had" },
  { verb: "know", chinese: "知道", past: "knew" },
  { verb: "make", chinese: "制造", past: "made" },
  { verb: "ride", chinese: "骑，乘", past: "rode" },
  { verb: "meet", chinese: "遇见", past: "met" },
  { verb: "speak", chinese: "讲话", past: "spoke" },
  { verb: "will", chinese: "将，愿", past: "would" },
  { verb: "ring", chinese: "鸣，响", past: "rang" },
  { verb: "run", chinese: "跑", past: "ran" },
  { verb: "stand", chinese: "站立", past: "stood" },
  { verb: "understand", chinese: "理解", past: "understood" },
  { verb: "wake", chinese: "醒", past: "woke" },
  { verb: "wear", chinese: "穿", past: "wore" },
  { verb: "win", chinese: "赢", past: "won" },
  { verb: "tell", chinese: "告诉", past: "told" },
  { verb: "take", chinese: "拿走", past: "took" },
  { verb: "see", chinese: "看见", past: "saw" },
];

export type PresentParticiple = {
  verb: string;
  participle: string;
  chinese: string;
};

export const presentParticiples: PresentParticiple[] = [
  { verb: "admit", participle: "admitting", chinese: "承认" },
  { verb: "ban", participle: "banning", chinese: "禁止" },
  { verb: "begin", participle: "beginning", chinese: "开始" },
  { verb: "beg", participle: "begging", chinese: "乞讨" },
  { verb: "chat", participle: "chatting", chinese: "交流" },
  { verb: "clap", participle: "clapping", chinese: "鼓掌" },
  { verb: "control", participle: "controlling", chinese: "控制" },
  { verb: "cut", participle: "cutting", chinese: "切" },
  { verb: "dip", participle: "dipping", chinese: "浸" },
  { verb: "drag", participle: "dragging", chinese: "拖，拉" },
  { verb: "drop", participle: "dropping", chinese: "掉落" },
  { verb: "fan", participle: "fanning", chinese: "扇风" },
  { verb: "fit", participle: "fitting", chinese: "修理" },
  { verb: "forget", participle: "forgetting", chinese: "忘记" },
  { verb: "get", participle: "getting", chinese: "获得" },
  { verb: "hit", participle: "hitting", chinese: "打" },
  { verb: "hug", participle: "hugging", chinese: "拥抱" },
  { verb: "infer", participle: "inferring", chinese: "推断" },
  { verb: "let", participle: "letting", chinese: "让" },
  { verb: "man", participle: "manning", chinese: "操纵" },
  { verb: "net", participle: "netting", chinese: "用网捕" },
  { verb: "nod", participle: "nodding", chinese: "点头" },
  { verb: "occur", participle: "occurring", chinese: "发生" },
  { verb: "pat", participle: "patting", chinese: "轻拍" },
  { verb: "permit", participle: "permitting", chinese: "允许" },
  { verb: "pet", participle: "petting", chinese: "爱抚" },
  { verb: "pin", participle: "pinning", chinese: "别住" },
  { verb: "plan", participle: "planning", chinese: "计划" },
  { verb: "prefer", participle: "preferring", chinese: "偏爱" },
  { verb: "put", participle: "putting", chinese: "放置" },
  { verb: "refer", participle: "referring", chinese: "指，谈起" },
  { verb: "rob", participle: "robbing", chinese: "抢劫" },
  { verb: "set", participle: "setting", chinese: "设置" },
  { verb: "ship", participle: "shipping", chinese: "用船运送" },
  { verb: "shop", participle: "shopping", chinese: "购物" },
  { verb: "shut", participle: "shutting", chinese: "关闭" },
  { verb: "sit", participle: "sitting", chinese: "坐" },
  { verb: "skip", participle: "skipping", chinese: "遗漏" },
  { verb: "sob", participle: "sobbing", chinese: "抽泣" },
  { verb: "spit", participle: "spitting", chinese: "吐痰" },
  { verb: "split", participle: "splitting", chinese: "分裂" },
  { verb: "star", participle: "starring", chinese: "主演" },
  { verb: "step", participle: "stepping", chinese: "踏步" },
  { verb: "stop", participle: "stopping", chinese: "停止" },
  { verb: "swim", participle: "swimming", chinese: "游泳" },
  { verb: "tap", participle: "tapping", chinese: "轻敲" },
  { verb: "top", participle: "topping", chinese: "到达顶峰" },
  { verb: "trap", participle: "trapping", chinese: "诱捕" },
  { verb: "wag", participle: "wagging", chinese: "摇摆" },
  { verb: "win", participle: "winning", chinese: "赢取" },
  { verb: "wrap", participle: "wrapping", chinese: "包起来" },
];

export const continuousExamples = [
  { present: "I am doing my homework now.", past: "I was doing my homework at this time yesterday." },
  { present: "We are cooking for our parents for the time being.", past: "We were cooking for our parents at that time." },
  { present: "They are having a meeting so far.", past: "They were having a meeting when I came in." },
  { present: "My friends are learning English these days.", past: "My friends were learning English those days." },
];

export const verbExamples = [
  "I was a child ten years old.",
  "I broke the glass yesterday.",
  "He bought a cup last night.",
  "I drew a picture 1 year ago.",
  "I spent 2 hours on my work today.",
  "He found two cats yesterday.",
  "I went to school last night.",
  "I put the cup on the table last week.",
  "He gave me a cake just now.",
  "I wrote a letter two hours ago.",
  "I sat on the table for a while.",
  "I left school ten years ago.",
  "I swept the floor yesterday.",
  "I spoke to him 1 month ago.",
  "I stood there for five minutes.",
  "I told him the story just now.",
];
